name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  compiler-test:
    name: Compiler Tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/compiler
    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.2'

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            ccache \
            libcurl4-openssl-dev \
            googletest \
            libgtest-dev

      - name: Install LLVM 21
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y clang-21 lldb-21 lld-21 llvm-21-dev
          clang++-21 --version

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ runner.os }}-llvm-21
          append-timestamp: true

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=clang-21 \
            -DCMAKE_CXX_COMPILER=clang++-21 \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DLLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm

      - name: Build
        run: cmake --build build --parallel $(nproc)

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

  intellij-plugin-test:
    name: IntelliJ Plugin Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x packages/stride-plugin-intellij/gradlew

      - name: Run Tests
        working-directory: packages/stride-plugin-intellij
        run: ./gradlew test
  deploy:
    name: Documentation Site Deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd docs; npm install

      - name: Build documentation
        run: cd docs; npm run docs:build; touch .vitepress/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist